SistemasLegales/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemasLegales.Models.Entidades;
using SistemasLegales.Models.Extensores;
using SistemasLegales.Models.Utiles;

namespace SistemasLegales.Controllers
{
    [Authorize(Policy = "Administracion")]
    public class ActorController : Controller
    {
        private readonly SistemasLegalesContext db;

        public ActorController(SistemasLegalesContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            var lista = new List<Actor>();
            try
            {
                lista = await db.Actor.OrderBy(c => c.Nombres).ToListAsync();
            }
            catch (Exception)
            {
                TempData["Mensaje"] = $"{Mensaje.Error}|{Mensaje.ErrorListado}";
            }
            return View(lista);
        }
        
        public async Task<IActionResult> Gestionar(int? id)
        {
            try
            {
                ViewBag.accion = id == null ? "Crear" : "Editar";
                if (id != null)
                {
                    var actor = await db.Actor.FirstOrDefaultAsync(c => c.IdActor == id);
                    if (actor == null)
                        return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");

                    return View(actor);
                }
                return View();
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.ErrorCargarDatos}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Gestionar(Actor actor)
        {
            try
            {
                ViewBag.accion = actor.IdActor == 0 ? "Crear" : "Editar";
                if (ModelState.IsValid)
                {
                    var existeRegistro = false;
                    if (actor.IdActor == 0)
                    {
                        if (!await db.Actor.AnyAsync(c => c.Nombres.ToUpper().Trim() == actor.Nombres.ToUpper().Trim()))
                            db.Add(actor);
                        else
                            existeRegistro = true;
                    }
                    else
                    {
                        if (!await db.Actor.Where(c => c.Nombres.ToUpper().Trim() == actor.Nombres.ToUpper().Trim()).AnyAsync(c => c.IdActor != actor.IdActor))
                            db.Update(actor);
                        else
                            existeRegistro = true;
                    }
                    if (!existeRegistro)
                    {
                        await db.SaveChangesAsync();
                        return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                    }
                    else
                        return this.VistaError(actor, $"{Mensaje.Error}|{Mensaje.ExisteRegistro}");
                }
                return this.VistaError(actor, $"{Mensaje.Error}|{Mensaje.ModeloInvalido}");
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.Excepcion}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                var actor = await db.Actor.FirstOrDefaultAsync(m => m.IdActor == id);
                if (actor != null)
                {
                    db.Actor.Remove(actor);
                    await db.SaveChangesAsync();
                    return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                }
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.BorradoNoSatisfactorio}");
            }
        }
    }
}

SistemasLegales/Controllers/CiudadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemasLegales.Models.Entidades;
using SistemasLegales.Models.Extensores;
using SistemasLegales.Models.Utiles;

namespace SistemasLegales.Controllers
{
    [Authorize(Policy = "Administracion")]
    public class CiudadController : Controller
    {
        private readonly SistemasLegalesContext db;

        public CiudadController(SistemasLegalesContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            var lista = new List<Ciudad>();
            try
            {
                lista = await db.Ciudad.OrderBy(c => c.Nombre).ToListAsync();
            }
            catch (Exception)
            {
                TempData["Mensaje"] = $"{Mensaje.Error}|{Mensaje.ErrorListado}";
            }
            return View(lista);
        }
        
        public async Task<IActionResult> Gestionar(int? id)
        {
            try
            {
                ViewBag.accion = id == null ? "Crear" : "Editar";
                if (id != null)
                {
                    var ciudad = await db.Ciudad.FirstOrDefaultAsync(c => c.IdCiudad == id);
                    if (ciudad == null)
                        return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");

                    return View(ciudad);
                }
                return View();
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.ErrorCargarDatos}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Gestionar(Ciudad ciudad)
        {
            try
            {
                ViewBag.accion = ciudad.IdCiudad == 0 ? "Crear" : "Editar";
                if (ModelState.IsValid)
                {
                    var existeRegistro = false;
                    if (ciudad.IdCiudad == 0)
                    {
                        if (!await db.Ciudad.AnyAsync(c => c.Nombre.ToUpper().Trim() == ciudad.Nombre.ToUpper().Trim()))
                            db.Add(ciudad);
                        else
                            existeRegistro = true;
                    }
                    else
                    {
                        if (!await db.Ciudad.Where(c => c.Nombre.ToUpper().Trim() == ciudad.Nombre.ToUpper().Trim()).AnyAsync(c => c.IdCiudad != ciudad.IdCiudad))
                            db.Update(ciudad);
                        else
                            existeRegistro = true;
                    }
                    if (!existeRegistro)
                    {
                        await db.SaveChangesAsync();
                        return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                    }
                    else
                        return this.VistaError(ciudad, $"{Mensaje.Error}|{Mensaje.ExisteRegistro}");
                }
                return this.VistaError(ciudad, $"{Mensaje.Error}|{Mensaje.ModeloInvalido}");
            }
            catch (Exception ex)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.Excepcion}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                var ciudad = await db.Ciudad.FirstOrDefaultAsync(m => m.IdCiudad == id);
                if (ciudad != null)
                {
                    db.Ciudad.Remove(ciudad);
                    await db.SaveChangesAsync();
                    return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                }
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.BorradoNoSatisfactorio}");
            }
        }
    }
}

SistemasLegales/Controllers/ProcesoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemasLegales.Models.Entidades;
using SistemasLegales.Models.Extensores;
using SistemasLegales.Models.Utiles;

namespace SistemasLegales.Controllers
{
    [Authorize(Policy = "Administracion")]
    public class ProcesoController : Controller
    {
        private readonly SistemasLegalesContext db;

        public ProcesoController(SistemasLegalesContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            var lista = new List<Proceso>();
            try
            {
                lista = await db.Proceso.OrderBy(c => c.Nombre).ToListAsync();
            }
            catch (Exception)
            {
                TempData["Mensaje"] = $"{Mensaje.Error}|{Mensaje.ErrorListado}";
            }
            return View(lista);
        }
        
        public async Task<IActionResult> Gestionar(int? id)
        {
            try
            {
                ViewBag.accion = id == null ? "Crear" : "Editar";
                if (id != null)
                {
                    var proceso = await db.Proceso.FirstOrDefaultAsync(c => c.IdProceso == id);
                    if (proceso == null)
                        return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");

                    return View(proceso);
                }
                return View();
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.ErrorCargarDatos}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Gestionar(Proceso proceso)
        {
            try
            {
                ViewBag.accion = proceso.IdProceso == 0 ? "Crear" : "Editar";
                if (ModelState.IsValid)
                {
                    var existeRegistro = false;
                    if (proceso.IdProceso == 0)
                    {
                        if (!await db.Proceso.AnyAsync(c => c.Nombre.ToUpper().Trim() == proceso.Nombre.ToUpper().Trim()))
                            db.Add(proceso);
                        else
                            existeRegistro = true;
                    }
                    else
                    {
                        if (!await db.Proceso.Where(c => c.Nombre.ToUpper().Trim() == proceso.Nombre.ToUpper().Trim()).AnyAsync(c => c.IdProceso != proceso.IdProceso))
                            db.Update(proceso);
                        else
                            existeRegistro = true;
                    }
                    if (!existeRegistro)
                    {
                        await db.SaveChangesAsync();
                        return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                    }
                    else
                        return this.VistaError(proceso, $"{Mensaje.Error}|{Mensaje.ExisteRegistro}");
                }
                return this.VistaError(proceso, $"{Mensaje.Error}|{Mensaje.ModeloInvalido}");
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.Excepcion}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                var proceso = await db.Proceso.FirstOrDefaultAsync(m => m.IdProceso == id);
                if (proceso != null)
                {
                    db.Proceso.Remove(proceso);
                    await db.SaveChangesAsync();
                    return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                }
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.BorradoNoSatisfactorio}");
            }
        }
    }
}

SistemasLegales/Controllers/ProyectoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemasLegales.Models.Entidades;
using SistemasLegales.Models.Extensores;
using SistemasLegales.Models.Utiles;

namespace SistemasLegales.Controllers
{
    [Authorize(Policy = "Administracion")]
    public class ProyectoController : Controller
    {
        private readonly SistemasLegalesContext db;

        public ProyectoController(SistemasLegalesContext context)
        {
            db = context;   
            
        }

        public async Task<IActionResult> Index()
        {
            var lista = new List<Proyecto>();
            try
            {
                lista = await db.Proyecto.OrderBy(c => c.Nombre).ToListAsync();
            }
            catch (Exception)
            {
                TempData["Mensaje"] = $"{Mensaje.Error}|{Mensaje.ErrorListado}";
            }
            return View(lista);
        }

        public async Task<IActionResult> Gestionar(int? id)
        {
            try
            {
                ViewBag.accion = id == null ? "Crear" : "Editar";
                if (id != null)
                {
                    var proyecto = await db.Proyecto.FirstOrDefaultAsync(c => c.IdProyecto == id);
                    if (proyecto == null)
                        return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");

                    return View(proyecto);
                }
                return View();
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.ErrorCargarDatos}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Gestionar(Proyecto proyecto)
        {
            try
            {
                ViewBag.accion = proyecto.IdProyecto == 0 ? "Crear" : "Editar";
                if (ModelState.IsValid)
                {
                    var existeRegistro = false;
                    if (proyecto.IdProyecto == 0)
                    {
                        if (!await db.Proyecto.AnyAsync(c => c.Nombre.ToUpper().Trim() == proyecto.Nombre.ToUpper().Trim()))
                            db.Add(proyecto);
                        else
                            existeRegistro = true;
                    }
                    else
                    {
                        if (!await db.Proyecto.Where(c => c.Nombre.ToUpper().Trim() == proyecto.Nombre.ToUpper().Trim()).AnyAsync(c => c.IdProyecto != proyecto.IdProyecto))
                            db.Update(proyecto);
                        else
                            existeRegistro = true;
                    }
                    if (!existeRegistro)
                    {
                        await db.SaveChangesAsync();
                        return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                    }
                    else
                        return this.VistaError(proyecto, $"{Mensaje.Error}|{Mensaje.ExisteRegistro}");
                }
                return this.VistaError(proyecto, $"{Mensaje.Error}|{Mensaje.ModeloInvalido}");
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.Excepcion}");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                var proyecto = await db.Proyecto.FirstOrDefaultAsync(m => m.IdProyecto == id);
                if (proyecto != null)
                {
                    db.Proyecto.Remove(proyecto);
                    await db.SaveChangesAsync();
                    return this.Redireccionar($"{Mensaje.Informacion}|{Mensaje.Satisfactorio}");
                }
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.RegistroNoEncontrado}");
            }
            catch (Exception)
            {
                return this.Redireccionar($"{Mensaje.Error}|{Mensaje.BorradoNoSatisfactorio}");
            }
        }


    }
}

SistemasLegales/Views/Shared/_Badge.cshtml
@model Requisito
@{
                int semaforo = Model.ObtenerSemaforo();
                string dias = Model.ObtenerDias();

    if (semaforo == 1)
    {
        <span class="label label-success col-lg-12">@dias</span>
    }
    else if (semaforo == 2)
    {
        <span class="label bg-yellow col-lg-12">@dias</span>
    }
    else
    {
        <span class="label label-danger col-lg-12">@dias</span>
    }
}

SistemasLegales/Views/Shared/_BootboxPartial.cshtml
<script src="~/lib/bootbox/bootbox.min.js"></script>
<script src="~/lib/assets/js/pages/ui/bootbox-animate.js"></script>
<script src="~/js/bootbox/bootbox.js"></script>

SistemasLegales/Views/Shared/_CambiarHabilitar.cshtml
@{
    string valorAuxiliar = ViewBag.ValorAuxiliar;
}
<form asp-action="CambiarHabilitar" class="hide" id="formCambiarHabilitar">
    @Html.Hidden("idRequisito")
    @Html.Hidden("valorAuxiliar", valorAuxiliar)
    <button type="submit" class="btn btn-primary" id="btn-eliminar">Aceptar</button>
</form>

SistemasLegales/Views/Shared/_DatatablesCSSPartial.cshtml
<link href="~/lib/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/jquery-datatable/skin/bootstrap/css/responsive.bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/jquery-datatable/skin/bootstrap/css/scroller.bootstrap.min.css" rel="stylesheet" />
<link href="~/lib/jquery-datatable/skin/bootstrap/css/fixedHeader.bootstrap.min.css" rel="stylesheet" />

SistemasLegales/Views/Shared/_FileInputScriptsPartial.cshtml
<script src='~/lib/bootstrap-fileinput/js/fileinput.min.js'></script>
<script src='~/lib/bootstrap-fileinput/js/locales/es.js'></script>

SistemasLegales/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
    <title>Sistemas legales</title>

    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/node-waves/waves.min.css" rel="stylesheet" />
    <link href="~/lib/animate-css/animate.min.css" rel="stylesheet" />
    <link href="~/lib/spinkit/spinkit.min.css" rel="stylesheet" />

    <link href="~/lib/toastr-notification/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/css/font-awesome.css" />
    @RenderSection("CSS", required: false)

    <link href="~/lib/assets/css/style.min.css" rel="stylesheet" />
    <link href="~/lib/assets/css/layout.min.css" rel="stylesheet" />
    <link href="~/lib/assets/css/themes/main_theme.min.css" rel="stylesheet" />

    <link href="~/lib/waitMe/waitMe.min.css" rel="stylesheet" />
    <link href="~/css/site.min.css" rel="stylesheet" />
</head>
<body class="theme-blue light layout-fixed">
    <div class="wrapper">
        <div class="page-loader-wrapper">
            <div class="loader">
                <div class="sk-wave">
                    <div class="sk-rect sk-rect1 bg-cyan"></div>
                    <div class="sk-rect sk-rect2 bg-cyan"></div>
                    <div class="sk-rect sk-rect3 bg-cyan"></div>
                    <div class="sk-rect sk-rect4 bg-cyan"></div>
                    <div class="sk-rect sk-rect5 bg-cyan"></div>
                </div>
                <p>Cargando...</p>
            </div>
        </div>
        <header class="topnavbar-wrapper">
            <nav role="navigation" class="navbar topnavbar">
                <div class="navbar-header">
                    <a asp-action="Index" asp-controller="Principal" class="navbar-brand">
                        <div class="brand-logo">
                            <img src="~/images/logo ideal.jpg" alt="Admin Logo" class="img-responsive logoposition" />
                        </div>
                        <div class="brand-logo-collapsed">
                            <img src="~/images/logosimple.png" alt="Admin Logo" class="img-responsive" />
                        </div>
                    </a>
                </div>
                <div class="nav-wrapper">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" data-trigger-resize="" data-toggle-state="aside-collapsed" class="hidden-xs">
                                <em class="material-icons">menu</em>
                            </a>
                            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
                                <em class="material-icons">menu</em>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a asp-action="ChangePassword" asp-controller="Manage">
                                <em class="material-icons">lock_open</em>
                                <span style="position:relative;bottom:5px;">Cambiar contrase&ntilde;a</span>
                            </a>
                        </li>
                        <li>
                            <a asp-action="Logout" asp-controller="Account">
                                <em class="material-icons">exit_to_app</em>
                                <span style="position:relative;bottom:5px;">Salir</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="aside">
            <div class="aside-inner">
                <nav data-sidebar-anyclick-close="" class="sidebar">
                    <ul class="nav menu">
                        <li class="nav-heading ">
                            <span>SISTEMA</span>
                        </li>
                        <li class="">
                            <a asp-action="Index" asp-controller="Principal" title="Principal">
                                <em class="material-icons">dashboard</em>
                                <span>Principal</span>
                            </a>
                        </li>
                        @{
                            if (User.IsInRole(Perfiles.Gestor))
                            {
                                <li class="nav-heading ">
                                    <span class="negrita">-ADMINISTRACIÓN</span>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Requisito" title="Gestión de requisitos">
                                        <span>Gestión de requisitos</span>
                                    </a>
                                </li>
                                <li class="nav-heading ">
                                    <span class="negrita">-HIST&Oacute;RICOS</span>
                                </li>
                                <li>
                                    <a asp-action="IndexFinalizado" asp-controller="Requisito" title="Requisitos finalizados">
                                        <span>Requisitos finalizados</span>
                                    </a>
                                </li>

                            }

                            if (User.IsInRole(Perfiles.Administrador))
                            {
                                <li class="nav-heading ">
                                    <span class="negrita">-ADMINISTRACIÓN</span>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Requisito" title="Gestión de requisitos">
                                        <span>Gestión de requisitos</span>
                                    </a>
                                </li>

                                <li class="nav-heading ">
                                    <span class="negrita">-MANTENIMIENTO</span>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="OrganismoControl" title="Organismos de control">
                                        <span>Organismos de control</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="RequisitoLegal" title="Bases legales">
                                        <span>Bases legales</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Ciudad" title="Ciudades">
                                        <span>Ciudades</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Proceso" title="Procesos">
                                        <span>Procesos</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Proyecto" title="Proyecto">
                                        <span>Proyectos</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Actor" title="Actores">
                                        <span>Actores</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Documento" title="Requisitos">
                                        <span>Requisitos</span>
                                    </a>
                                </li>

                            }

                            if (User.IsInRole(Perfiles.Gerencia))
                            {
                                <li class="nav-heading ">
                                    <span class="negrita">-GESTIÓN GERENCIAL</span>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Requisito" title="Estado de requisitos">
                                        <span>Estado de requisitos</span>
                                    </a>
                                </li>
                            }

                            if (User.IsInRole(Perfiles.Administrador))
                            {
                                <li class="nav-heading ">
                                    <span class=" negrita">-USUARIOS</span>
                                </li>
                                <li>
                                    <a asp-action="Users" asp-controller="Account" title="Gestión de usuarios">
                                        <span>Gestión de usuarios</span>
                                    </a>
                                </li>
                                <li class="nav-heading ">
                                    <span class="negrita">-HIST&Oacute;RICOS</span>
                                </li>
                                <li>
                                    <a asp-action="IndexFinalizado" asp-controller="Requisito" title="Requisitos finalizados">
                                        <span>Requisitos finalizados</span>
                                    </a>
                                </li>
                            }

                        }
                    </ul>
                </nav>
            </div>
        </aside>
        <section>
            <div class="content-wrapper">
                <div class="container-fluid">
                    <div class="page-header">
                        <h2>@ViewData["Titulo"]</h2>
                        <ol class="breadcrumb">
                            <li><a asp-action="Index" asp-controller="Principal">Principal</a></li>
                            @RenderSection("Migas", required: false)
                        </ol>
                    </div>
                    <div class="row clearfix">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="card" id="divCard">
                                <div class="card-header">
                                    <h2>
                                        @ViewData["Subtitulo"]
                                    </h2>
                                </div>
                                <div class="body" id="bodyTemplate">
                                    @RenderBody()
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer>
            <span>&copy; 2018 - Sistemas legales</span>
        </footer>
        <span class="hide" id="spanMensaje">@TempData["Mensaje"]</span>
    </div>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/modernizr/modernizr.custom.js"></script>
    <script src="~/lib/screenfull/dist/screenfull.min.js"></script>
    <script src="~/lib/jQuery-Storage-API/jquery.storageapi.js"></script>
    <script src="~/lib/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/lib/node-waves/waves.min.js"></script>
    <script src="~/js/app/miApp.min.js"></script>

    <script src="~/lib/toastr-notification/toastr.min.js"></script>
    <script src="~/js/toastr/mensajes.min.js"></script>

    <script src="~/lib/ladda/spin.min.js"></script>
    <script src="~/lib/ladda/ladda.min.js"></script>

    <script src="~/js/moment/moment.js"></script>
    <script src="~/js/moment/moment-with-locales.js"></script>

    <script src='~/lib/waitMe/waitMe.min.js'></script>
    <script src="~/js/waitMe/waitMe.min.js"></script>

    @RenderSection("Scripts", required: false)

    <script src="~/lib/assets/js/demo.min.js"></script>
    <script src="~/lib/assets/js/layout.min.js"></script>
    <script src="~/js/app/site.min.js"></script>
</body>
</html>